name: Checking test

# 1. Check current directory and list files
pwd
ls -l

# 2. If 'build.sh' is not listed or has incorrect permissions:
#    - If it's in a subdirectory, navigate there or use the full path.
#    - If permissions are missing (e.g., '-rw-r--r--'), add execute permission:
chmod +x build.sh

# 3. Try running the script again
./build.sh
        name: Android Kernel Release | ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          ## Build Information
          Manifest: ${{ inputs.MANIFEST_URL }}/tree/${{ inputs.MANIFEST_BRANCH }}
